### ISSUE TITLE
Address bar location is not updated when toggling [Router] actions in devtools

### ISSUE THREAD

**Issue by pmulac** [ngrx/router-store#1]
When you "undo" router actions via ngrx/devtools, the location path in the browser's address bar does not revert.

For example, say my app's home route is `/`.  If I navigate to `/routeA` with ngrx/router, the "update location" action fires and is displayed in the devtools, as expected.  If you toggle the action in the devtools, the route-view correctly reverts to the component associated with the `/` route.  However, the location displayed in the address bar remains as `/routeA`.

**Comment by MikeRyanDev** [comment]
That's correct behavior. It becomes a lot more complicated if you want the address bar to sync up as well, and it would muck up the browser's history stack with a lot of extra push/replace calls.

Going to close this but feel free to discuss if this is something you would want in the future.
