### ISSUE TITLE
Question: How can I evaluate some code to determine the route to navigate to?

### ISSUE THREAD

**Issue by firecube** [ngrx/router-store#13]
Hi,

I am loving all these ngrx libs.  

Right now I am using @effects which listen for my custom router actions e.g. CUSTOMER_PAGE_FORWARD and then navigate with the Angular router.  If the state needs to be interrogated to determine where to navigate I can do this directly in the @effect.  This way, my pages can be dumb and just do something like this.store.dispatch(this.routingActions.customerForward())

What is the best way to do this with router-store?  Where should this code go?  

Thanks, Simon

**Comment by brandonroberts** [comment]
You would map your custom router action to a router-store action and that action will be picked up and navigation would occur.

**Comment by firecube** [comment]
Would you mind giving a quick example? 

Thanks, Simon

**Comment by brandonroberts** [comment]
``` ts
import {go} from '@ngrx/router-store';

@Effect()
this.customerForward$ = this.action$.ofType(CUSTOMER_PAGE_FORWARD)
  .map(() => go(['/somewhere']));
```

**Comment by firecube** [comment]
So basically, exactly how I have it now!  

Thanks so much @brandonroberts.

**Comment by IliaIdakiev** [comment]
I'm having trouble navigating with router-store in a lazy loaded module. I'm doing the same thing as shown by @brandonroberts but nothing is happening. Is there something additional that I have to include in my lazy loaded ngmodule for it to work?

**Comment by brandonroberts** [comment]
@IliaIdakiev can you provide an example of what you're trying to do? Preferably in a new issue since this issue is closed.
