### ISSUE TITLE
Default value of state in routerReducer is null which causes store-log-monitor to error on a reset

### ISSUE THREAD

**Issue by firecube** [ngrx/router-store#14]
As the state defaults to null in the reducer clicking reset in the dev tools throws an error...

Cannot read property 'path' of null.

If I edit the line in reducer.js to the line below it works fine in my app but not sure if there are any wider implication or a better fix.

 if (state === void 0) { state = { path: '' }; }

**Comment by firecube** [comment]
I can also get round this issue by doing this in my app module which may be the recommended approach rather than just a work around.

StoreModule.provideStore(reducer, { router: { path: '' } })

**Comment by MrChoclate** [comment]
What about  `window.location.pathname` ?

**Comment by brandonroberts** [comment]
Setting this initial value for the reducer is the recommended approach. I didn't want to set the initial value using `window.location` so it would be safe to use where `window` isn't available.

**Comment by firecube** [comment]
Thanks @brandonroberts, I will use the initial value.

I do wonder whether this should also default in the router-store code as without this the ngrx store-log-monitor reset button causes the app to crash.

**Comment by brandonroberts** [comment]
I'll add it to the README for defaulting to an initial value
