### ISSUE TITLE
error while navigation

### ISSUE THREAD

**Issue by ritz078** [ngrx/router-store#21]
I am getting the following error when I am navigating from one url to another using 'routerLink'.

<img width="859" alt="screen shot 2016-09-15 at 7 54 25 pm" src="https://cloud.githubusercontent.com/assets/5389035/18553542/6e602c3c-7b7e-11e6-9bc9-0378c4c3a7c4.png">

when i remove `RouterStoreModule.connectRouter()` from `app.module.ts`, the error disappears.

**Comment by brandonroberts** [comment]
What's in your `routerLink`?

**Comment by ritz078** [comment]
`'/login'`

**Comment by monad98** [comment]
same problem with v1.2.2

**Comment by monad98** [comment]
This error happens only with "@ngrx/core": "1.2.0",
