### ISSUE TITLE
state.path is null which causes store-log-monitor to error on a reset/revert

### ISSUE THREAD

**Issue by avoskresensky** [ngrx/router-store#26]
This is related to #14 and #24.
After the fix made in v1.2.4 store-log-monitor still crashes but for a different reason.
The error is now inside Router.navigateByUrl which is being passed a null which it cannot handle.

The fix seems to be pretty simple: listenForStoreChanges function

`//newPath$.subscribe(url => router.navigateByUrl(url));`
`newPath$.subscribe(url => url && router.navigateByUrl(url));`

**Comment by wizardnet972** [comment]
For now I did this fix:
https://github.com/wizardnet972/tic-tac-toe/blob/master/src/client/app/shared/store.ts#L34

until the bug resolve.
