### ISSUE TITLE
Javascript not include

### ISSUE THREAD

**Issue by thaoula** [ngrx/router-store#28]
Hi guys,

Just want to confirm. Is NPM supposed to include a javascript file to use? 

Currently it only include the TS files.

If yes, is the idea that I copy the src to my project?

Regards,
Tarek

**Comment by brandonroberts** [comment]
The NPM release only includes javascript and TypeScript definition files. No TS files.

**Comment by thaoula** [comment]
I just deleted the reference in package JSON and added it again. Seems to have brought back the correct JS files and umd builds. 

I did notice that the package.json made reference to "github:version" rather than "^1.2.5".

**Comment by brandonroberts** [comment]
How did you install it?

**Comment by thaoula** [comment]
I am pretty sure i just used npm install ... however, I did also use yarn which seemd to update to the latest version. 

I definitely did not manually add it to project.json
