### ISSUE TITLE
Support static and resolved route data

### ISSUE THREAD

**Issue by sliekens** [ngrx/router-store#33]
The Angular 2 router supports routes with static and/or lazily loaded data using resolve services. Currently I do not see any support for that in ngrx/router-store. I also don't see it being discussed anywhere.

You can find a high-level description of route data and resolve services here: https://vsavkin.com/angular-2-router-d9e30599f9ea#.rxc9egybq

My feature request is that actions of type `[Router] Update Location` should get all static and resolved state of the current `ActivatedRouteSnapshot` and put it in the store. So basically get the value of `ActivatedRoute.snapshot.data` when the route changes and put it in the store.

Code examples available on demand

**Comment by sliekens** [comment]
I wrote an Effect that puts the current route's data in the store when `[Router] Update Location` is observed.

```ts
// router-data.effects.ts
import { Injectable } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Actions, Effect } from '@ngrx/effects';
import { routerActions } from '@ngrx/router-store';

import { DataAction } from '../actions/router-data.actions';

@Injectable()
export class RouterDataEffects {
  @Effect() data$ = this.actions$
    .ofType(routerActions.UPDATE_LOCATION)
    .map(action => new DataAction(this.route.snapshot.data));

  constructor(private actions$: Actions, private route: ActivatedRoute) {
  }
}
```

```ts
// router-data.actions.ts
import { type } from '../util';
import { Action } from '@ngrx/store';
import { Data } from '@angular/router';

export const ActionType = {
  DATA: type('[Router Data] Data')
};

export class DataAction implements Action {
  public type: string = ActionType.DATA;
  constructor(public payload: Data) {
  }
}

export type Actions = DataAction;
```
```ts
// router-data.reducer.ts
import { Data } from '@angular/router';
import { ActionType, Actions } from '../actions/router-data.actions';

export interface State {
  data: Data;
}

const initalState: State = { data: {} };

export function reducer(state: State = initalState, action: Actions) {
  switch (action.type) {
    case ActionType.DATA:
      return { data: action.payload };
    default:
      return state;
  }
}
```

---

The result is a state object that looks like so:
```ts
{
  router: {
    path: '/locations'
  },
  routerData: {
    data: {
      'staticValue': 'This is static route data',
      'resolvedValue': 'This is resolved data'
    }
  }
}
```

It would be nice if my reducer could be merged into yours so that everything is contained in the `router` slice.

```ts
// In a perfect world
{
  router: {
    path: '/locations',
    data: {
      'staticValue': 'This is static route data',
      'resolvedValue': 'This is resolved data'
    }
  }
}
```

**Comment by JBusch** [comment]
Looks really nice. I think that this is a nice and necessary feature.

**Comment by brandonroberts** [comment]
This works fine if you only have one level of routes with data, but each level in your configuration can have route data.  So you'd have to collect all the route data from each level and avoid naming collisions. 

Another issue is what kind of route data you're storing. The data in the state should be serializable to JSON so you can export/import it. If you're storing resolved instances of data, that data won't be easy serialized back and forth if you wanted to export and import your state.

**Comment by sliekens** [comment]
@brandonroberts, I don't understand how having multiple levels creates a difference. Can navigation to a (deeply) nested route result in there being more than a single instance of `ActivatedRoute`?

For the second issue: is it really an issue if the route data from a previous navigation event is not correctly (de-)serialized? Regardless of what route data is imported, the next navigation event replaces whatever route data was imported to the store.

**Comment by brandonroberts** [comment]
@StevenLiekens yes, there isn't just one `ActivatedRoute`. There is a tree of `ActivatedRoute`s that is composed of each route in a navigation event and each route component has its own `ActivatedRoute`.

As far as serialization, it comes more into play if you want to use the devtools to debug and walk back through your actions that changed your state. I'm not saying your use case isn't valid. Just wanting to look at the overall impact.

**Comment by philipbulley** [comment]
Replicating router state in the store sounds incredibly useful (ie. for use in selectors). At the very least, data derived directly from the URL itself like `queryParams`, `params`, etc. Considering the tree of `ActivatedRoute`s, what might this look like within the store?

**Comment by brandonroberts** [comment]
Victor Savkin has prototyped replicating the router state in the store here which contains params and static data. https://github.com/vsavkin/router-store-prototype

**Comment by brandonroberts** [comment]
These changes have been implemented in the monorepo where we are migrating the packages: https://github.com/ngrx/platform

**Comment by clavecoder** [comment]
When will this be released? When it is released, how will the API change?

**Comment by talamaska** [comment]
Where is this implemented in Platform? Via the RouterStateSerializer? Not sure but I'm having issues getting the data of a child route

**Comment by attilacsanyi** [comment]
Dear @talamaska afaik you can define your custom `RouterStateSerializer` which read the `data` property based on `ActivatedRouteSnapshot`
```
export declare class ActivatedRouteSnapshot {
    /** The URL segments matched by this route */
    url: UrlSegment[];
    /** The matrix parameters scoped to this route */
    params: Params;
    /** The query parameters shared by all the routes */
    queryParams: Params;
    /** The URL fragment shared by all the routes */
    fragment: string;
    /** The static and resolved data of this route */
    data: Data; <-- You need THIS I guess
    ...
}
```

I hope this helps.

**Comment by talamaska** [comment]
@attilacsanyi thanks
