### ISSUE TITLE
Problem dispatching GO action using effects in a lazy loaded module

### ISSUE THREAD

**Issue by IliaIdakiev** [ngrx/router-store#37]
Hello. 
I'm having a problem dispatching router-store actions inside a lazy loaded module. Inside the module I also have sub routing. The effect looks something like:

```javascript
@Effect()
    back$: Observable<Action> = this.actions$.ofType(actions.ActionTypes.BACK)
        .map(() => go(['/lazyloaded/main/']));
```

Since its a lazy loaded module inside my main component for the module I'm using:
```javascript
store.replaceReducer(extendedAppReducer);
```

and in the module:

```javascript
StoreModule.provideStore(extendedAppReducer), //followed by EffectsModule.run( ...
```

While debugging the effect I saw is that ```listenForRouterMethodActions```  inside ```connect.ts``` is never called. I tried putting ```RouterStoreModule.connectRouter()``` into my lazy loaded module imports but no luck.

**Comment by brandonroberts** [comment]
@IliaIdakiev you should only include `RouterStoreModule.connectRouter()` in your `AppModule` `imports` and not in your lazy loaded module.

**Comment by IliaIdakiev** [comment]
@brandonroberts I was just testing because it's not working so thats why I put it.

**Comment by brandonroberts** [comment]
Can you provide more details about your setup? A reproduction in a plunker would also help

**Comment by IliaIdakiev** [comment]
https://plnkr.co/edit/nxUGgSA0VTitgyZRbcdX?p=preview

**Comment by brandonroberts** [comment]
The issue is that you're providing `StoreModule.provideStore(appReducerWithLazy),` as an import in your lazy loaded module. This is giving you another instance of Store since the Router creates a child injector for lazy loaded modules. You should only use the `StoreModule.provideStore` in your `AppModule`

Example: https://plnkr.co/edit/C0I1rW39ZefZJlUGdB08?p=preview

**Comment by IliaIdakiev** [comment]
I see. Is there a way I can separate the effects being loaded? I don't want to load all my effects in the main module.

**Comment by brandonroberts** [comment]
You can still lazy load your effects with your module. You just can't provide more than one instance of the Store. I wouldn't recommend lazy load those navigation effects though since you're likely going to use them across multiple modules.

**Comment by IliaIdakiev** [comment]
@brandonroberts 
So my problem was that in the effects I'm doing something like 

```javascript
.withLatestFrom(this._store$.select(s => getSomething(s)), (payload:any, something:any) => {
   ...
})
```
and I was getting an error of ```cannot get property something of undefined``` because I'm running the effects (in the lazy loaded module) before replacing the reducer (in the main component of the lazy loaded module). I changed it to:

```javascript
.withLatestFrom(this._store$, (payload:any, _store:any) => {
   let something = getSomething(_store);
   ...
})
```
and its working.

Because of this error I thought that I have to provide the store in the lazy loaded module and that is the reason why I was doing ```StoreModule.provideStore(appReducerWithLazy)```. Thanks for clarifying!
