### ISSUE TITLE
dispatching go

### ISSUE THREAD

**Issue by AndriiDidkivsky** [ngrx/router-store#41]
Hi, i have some routes. 
```
    {
        path: 'tasks/redflag',
        component: TaskList,
        children: [{
            path: ':id',
            component: TaskDetailResolverComponent
        }]
    },
```

When i'm on the tasks/redflag I try navigate to child route tasks/redflag/:id
`this.store.dispatch(go([task.Id], null,  { relativeTo: this.route }));`

But nothing happens. 

Could you provide any advices ? 
Thanks.

**Comment by awerlang** [comment]
Have you imported `RouterStoreModule.connectRouter()`?

**Comment by AndriiDidkivsky** [comment]
@awerlang , Of course. 
Everything works fine. When I open direct link `www.url/tasks/redflag/1` it works.
So absolute path works fine. Strange that
 `this.router.navigate([task.Id], { relativeTo: this.route })` 
doesn't work too. [Official documentation](https://angular.io/docs/ts/latest/guide/router.html) says that it should. 

Error from promise 'Cannot match any routes. URL Segment: 1'

**Comment by brandonroberts** [comment]
Where is `this.route` from? Are you doing this within an effect?

**Comment by AndriiDidkivsky** [comment]
@brandonroberts , `this.route `is `ActivatedRoute` that already injected into component constructor.
Dispatching happens directly in the component. I can migrate this code in Effects but don't see any reasons to do it now. Because it just doesn't work in any places. 

It works fine if I dispatching absolute path `this.store.dispatch(go(['tasks/redflag/1']));`

**Comment by brandonroberts** [comment]
No need to, just trying to get a frame of reference. You're dispatching this action from the `TaskList` component where you've injected `ActivatedRoute`, correct?

**Comment by AndriiDidkivsky** [comment]
Absolutely correct.

**Comment by AndriiDidkivsky** [comment]
I can provide more info about the project.

**Comment by brandonroberts** [comment]
Yes, that would help. If you could reproduce in a plunker that would be even better.

**Comment by AndriiDidkivsky** [comment]
ok, thanks. I'll try to do that in the near future.

**Comment by brandonroberts** [comment]
For debugging purposes, will you add this to your `RouterModule.forRoot(routes)`

`RouterModule.forRoot(routes, { enableTracing: true })`

Then open up your developer console and paste what it says when you try to navigate there

**Comment by AndriiDidkivsky** [comment]
@brandonroberts , I've changed  
`this.router.navigate([task.Id], { relativeTo: this.route })  `
to 
`this.router.navigate([task.Id], { relativeTo: this.route.firstChild })`
Everything fine now. Thanks, I close issue,

**Comment by AndriiDidkivsky** [comment]
Hi' again.
I've found that ActivatedRoute always contains root component.
I think it's configuration issue, but i don't know how to resolve  it.

**Comment by AndriiDidkivsky** [comment]
I've found solution. It's just my mistake.
