### ISSUE TITLE
Add route params to the payload

### ISSUE THREAD

**Issue by RPDeshaies** [ngrx/router-store#43]
It would be nice if the route params would be inserted inside the payload of the action so a route like : 

`/user/:id`

would give something like
```
{
  path : '/user/123123'
  params : {
    id : '123123'
  }
}
```

That way, every component inside the app (that is not directly the Route Component) could subscribe  to route params

**Comment by gausie** [comment]
Modifying the action payload sounds like a bad idea but it would be good to have a discussion on accessing the route params in a more reduxy way

**Comment by brandonroberts** [comment]
The next version of this library will have access to the router state, giving you access to the route params

**Comment by RPDeshaies** [comment]
That is awesome. When will this version be released ?

**Comment by brandonroberts** [comment]
We are targeting May at the latest for the next release. We are migrating the individual repos to a monorepo and getting the infrastructure together for that. Then we'll cut an alpha release for feedback.

**Comment by TylerYang** [comment]
Hi @brandonroberts Any plans for this feature?
