### ISSUE TITLE
Is this repo being maintaned?  If so, are there any plans to update/sync it with the syntax used in ngrx/example-app?

### ISSUE THREAD

**Issue by kemalcany** [ngrx/router-store#47]
Hi guys,

@brandonroberts @MikeRyan52  and others, this is a great library and thank you very much for providing it!

However, there hasn't been much activity here lately and it would be good to know if there are any plans to synchronise it with the rest of ngrx suite?

I have a feeling that the ngrx/example-app repo demonstrates the latest syntax and best practices to use the ngrx components (such as store, effects etc.). This might not be the case, but i think a lot of people (including me) are taking it as a reference. It would be nice to have some symmetry across the different libraries imo..

This repo is out of sync with the syntax there. For example, the actions doesn't export an Actions type (such as below, taken from the [example-app](https://github.com/ngrx/example-app/blob/b2aa4fe70400da223d8fe092befc38b9326945e3/src/app/actions/book.ts)

```
export type Actions
  = SearchAction
  | SearchCompleteAction
  | LoadAction
  | SelectAction;
```

Will there be any effort to implement a version like that? If not from you, would you welcome any help with that? 

Cheers

**Comment by llwt** [comment]
Looks like there is a new version of the project coming soon: See [vsavkin/router-store](https://github.com/vsavkin/router-store).

Ref #35
