### ISSUE TITLE
PeerDependency Complaining on @angular/core, @angular/common and @angular/router

### ISSUE THREAD

**Issue by ZheyangSong** [ngrx/router-store#50]
Would there be an update to support the Angular 4 related libs? Or is this lib being deprecated?

**Comment by s-ve** [comment]
Please correct me if I am wrong but it seems this library will be deprecated in favor of [this one](https://github.com/vsavkin/router-store).

**Comment by brandonroberts** [comment]
There is a new version coming with support for the latest Angular

**Comment by davefedele** [comment]
Any chance you can update your package.json to support angular 4. We're unable to use shrinkwrap because of the dependency errors. Thanks!
```
    "@angular/common": "^2.0.0  || ^4.0.0",
    "@angular/core": "^2.0.0 || ^4.0.0",
    "@angular/router": "^3.0.0  || ^4.0.0"
```
