### ISSUE TITLE
go(['/login']) doesn't update state router.path in Observables catch

### ISSUE THREAD

**Issue by prostoandrei** [ngrx/router-store#51]
I have a problem with router state update when I perform `this.store.dispatch(go(['/login']));`.

It works everywhere in my app, but not in this catch.

    return this.http.request(url, options).catch((error) => {
      if (
        error.json().code === ERRORS.INVALID_ACCESS_TOKEN ||
        error.json().code === ERRORS.ACCESS_TOKEN_EXPIRED
      ) {
        return this.token
         .getNewToken(null, this.token.getRefreshToken())
         .flatMap((token) => {
           this.token.setTokenObj(token);
           return this.request(url, options, data);
         })
         .catch((err) => {
           this.token.cleanToken();
           this.store.dispatch(go(['/login'])); // GO IS HERE
           return Observable.throw(err);
       });
    }})

Cause I can't perform `this.store.dispatch(go(['/home']))` because my state path is still /home.
Action `[Router] Go` was fired but `[Router] Update Location` wasn't.

Does it have problems in Observables catch?

**Comment by brandonroberts** [comment]
This is expected behavior from the router. If you're on that route and you navigate to the same URL, its not going to navigate again as its aggressive about reusing route components.

**Comment by prostoandrei** [comment]
@brandonroberts I don't think that it's expected behavior.

I have a state:
-> `router.path: '/home'`
Then I perform `this.store.dispatch(go(['/login']))` inside of my service method. Then I get state:
-> `router.path: '/home'` // still `/home` but it should be `/login`

Action `[Router] Go` was dispatched,  but `[Router] Update` Location wasn't.

When I perform `this.store.dispatch(go(['/home']))` again of course it doesn't work, because I have wrong state
