### ISSUE TITLE
router.navigate NavigationExtras has no replaceUrl

### ISSUE THREAD

**Issue by BrainCrumbz** [ngrx/router-store#9]
Not sure it's just us or what. In my team we're experimenting with latest router-store version taken from this repo (and importing it as `import ... from '@ngrx/router-store/lib';`.

When building, there's an error on _lib\connect.ts_:

```
(28,52): error TS2345: Argument of type '{ queryParams: any; replaceUrl: boolean; }' is not assignable to parameter of type 'NavigationExtras'.
  Object literal may only specify known properties, and 'replaceUrl' does not exist in type 'NavigationExtras'.
```

due to this line:

``` ts
router.navigate(commands, { queryParams, replaceUrl: true });
```

as, at least for current angular2 RC5, that `replaceUrl` field is not defined in type `NavigationExtras`.

Is it just us? Thanks

**Comment by brandonroberts** [comment]
Correct. It will come with RC6. A fix has been added for now.
